import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:nexapos_mobile/domain/services/nxpatch.dart';

void main() {
  // The fixtures are generated by a matching Python tool (see
  // scratchpad/make_nxpatch_fixtures.py, itself using
  // release-tools/nxpatch.py) - a genuine cross-language check that the
  // Dart applier here reads a patch the real generator actually
  // produces, not just a patch built by test code that shares its own
  // (possibly also wrong) assumptions.
  final fixturesDir = 'test/domain/services/fixtures';

  test('applies a real cross-language-generated patch and reconstructs the exact new file', () {
    final oldBytes = Uint8List.fromList(File('$fixturesDir/old.bin').readAsBytesSync());
    final newBytes = Uint8List.fromList(File('$fixturesDir/new.bin').readAsBytesSync());
    final patchBytes = Uint8List.fromList(File('$fixturesDir/patch.nxpatch').readAsBytesSync());

    final reconstructed = applyNxPatch(oldBytes, patchBytes);

    expect(reconstructed, equals(newBytes));
  });

  test('rejects a file that is not an NXPATCH1 patch', () {
    final oldBytes = Uint8List.fromList([1, 2, 3]);
    final notAPatch = Uint8List.fromList('not a patch at all, just text'.codeUnits);
    expect(
      () => applyNxPatch(oldBytes, notAPatch),
      throwsA(isA<NxPatchFormatException>()),
    );
  });

  test('rejects an original file too short for the patch\'s control block', () {
    final tooShortOldBytes = Uint8List.fromList(List.filled(100, 0));
    final patchBytes = Uint8List.fromList(File('$fixturesDir/patch.nxpatch').readAsBytesSync());

    expect(
      () => applyNxPatch(tooShortOldBytes, patchBytes),
      throwsA(isA<NxPatchFormatException>()),
    );
  });

  test(
    'the RIGHT-SIZED but wrong-content original file reconstructs garbage without throwing - '
    'this is exactly why the caller must verify the result\'s SHA-256, not trust this function alone',
    () {
      final wrongContentOldBytes = Uint8List.fromList(List.filled(10500, 0));
      final newBytes = Uint8List.fromList(File('$fixturesDir/new.bin').readAsBytesSync());
      final patchBytes = Uint8List.fromList(File('$fixturesDir/patch.nxpatch').readAsBytesSync());

      final reconstructed = applyNxPatch(wrongContentOldBytes, patchBytes);

      expect(reconstructed, isNot(equals(newBytes)));
    },
  );

  test('parses a multi-file patch bundle manifest', () {
    const json = '''
    {
      "files": [
        {"path": "data/app.so", "oldSha256": "aa", "newSha256": "bb", "patchFile": "patch_0.nxpatch"},
        {"path": "nexapos_mobile.exe", "oldSha256": "cc", "newSha256": "dd", "patchFile": "patch_1.nxpatch"}
      ]
    }
    ''';
    final entries = parseNxPatchManifest(json);
    expect(entries, hasLength(2));
    expect(entries[0].path, 'data/app.so');
    expect(entries[1].patchFile, 'patch_1.nxpatch');
  });
}
